name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Construir projeto
        run: npm run build

      - name: Upload do site para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '/dist'  # 🔴 Altere se o build estiver em outra pasta

      - name: Fazer deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4